language: python
cache: pip
dist: xenial
matrix:
    fast_finish: false
    include:

      - { python: "3.6", env: DJANGO=2.1}
      - { python: "3.6", env: DJANGO=2.2}
#      - { python: "3.6", env: DJANGO=3.0}
#      - { python: "3.6", env: DJANGO=master}


install:
    - pip install tox tox-venv tox-travis

script:
    - tox

notifications:
    email: false