from setuptools import setup, find_packages

setup(
    name="reinhardt",
    version="0.1a",
    author_email='devhelp@cce.ou.edu',
    description='A collection of Django tools created for ease of use and rapid development.',
    author='University of Oklahoma - College of Continuing Education - IT',
    license='BSD',
    install_requires=[
        "django-currentuser>=0.4.2",
        "arrow>=0.15.5",
        "openpyxl>=3.0.3",
        "django-tables2>=2.2.1",
        "django-crispy-forms>=1.8.1",
        "rules>=2.2",
        "psycopg2",
        "django-widget-tweaks",
        "django-simple-history==2.8.0",
    ],
    classifiers=[
        'Development Status :: 0.1a',
        'Environment :: Web Environment',
        'Framework :: Django',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: BSD License',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 2.7',
        'Topic :: Software Development :: Libraries :: Application Frameworks',
        'Topic :: Software Development :: Libraries :: Python Modules',
        ],
    url='https://github.com/cceit/django-dx',
    packages=find_packages(),
    include_package_data=True,
    zip_safe=False,
)
